import {SpatialPlant} from './spatial.mjs';
import {equipmentSvg,productForm} from './equipment.mjs';
import {createPlant,act,advance,summarise,assertPlant,exportRun,importRun,replayRun,scenario,tags,review,csv,permissives,commandStatus} from './engine.mjs';
import {VERSION,LIMITS,RECIPES,FAULTS,CLEAN_PHASES,SCENARIOS,SOURCES,ASSUMPTIONS} from './catalog.mjs';

const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,d=1)=>Number(v).toLocaleString('en-AU',{minimumFractionDigits:d,maximumFractionDigits:d});
const clock=s=>`${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor(s%3600/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
const routes=[['plant','Process overview'],['control','Control & I/O'],['production','Production & intake'],['quality','Quality & genealogy'],['utilities','Utilities & environment'],['maintenance','Maintenance & sanitation'],['alarms','Alarms & historian'],['integration','Integration lab'],['scenarios','Scenario studio'],['reference','Engineering reference']];
const initialPlant=()=>{const s=scenario('baseline');act(s,'stop');return s;};
let plant=initialPlant(),lens=null,selected='fry',playing=false,rate=10,route='plant',pending=null,filter='',noticeTimer;
let plantMode='model',overlay='status',showLabels=true,showServices=true,spatial=null,graphicsFailed=false;
const state=()=>lens||plant;
const readonly=()=>Boolean(lens);
const button=(label,cmd,id='',cls='')=>{const status=commandStatus(state(),cmd,id?{id}:{}),reason=readonly()?'Return to the present to operate':status.reason;return `<button type="button" class="${cls}" data-cmd="${cmd}" ${id?`data-id="${esc(id)}"`:''} ${reason?`disabled title="${esc(reason)}"`:''}>${label}</button>`;};
const action=(label,id,cls='')=>`<button type="button" class="${cls}" data-action="${id}">${label}</button>`;
const badge=(text)=>`<span class="state ${['TRIPPED','FAULT','TRIP','STALE','REJECTED'].includes(text)?'bad':['HELD','BLOCKED','HOLD','HIGH','PENDING','DIRTY','DRAINING'].includes(text)?'warn':['RUNNING','CLEAN','GOOD','RELEASED','COMPLETE','DELIVERED'].includes(text)?'good':''}">${esc(text)}</span>`;
const metric=(label,value,unit,help)=>`<div class="metric"><small>${label}</small><strong>${value} <span>${unit}</span></strong><em>${help}</em></div>`;
const card=(title,body,extra='')=>`<section class="card ${extra}"><h2>${title}</h2>${body}</section>`;
const table=(headers,rows,empty='No records yet. Run a scenario or operate the line to create them.')=>`<div class="table-wrap" tabindex="0"><table><thead><tr>${headers.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td class="empty" colspan="${headers.length}">${empty}</td></tr>`}</tbody></table></div>`;
const field=(label,name,value,opts='')=>`<label class="field">${label}<input name="${name}" value="${esc(value)}" ${opts}></label>`;
const options=(items,current)=>items.map(x=>`<option value="${esc(x.id)}" ${x.id===current?'selected':''}>${esc(x.name||x.id)}</option>`).join('');
const recipeName=id=>RECIPES.find(x=>x.id===id)?.name||id;
function form(cmd,content,label='Apply',id=''){return `<form data-form="${cmd}" ${id?`data-id="${id}"`:''}><fieldset ${readonly()?'disabled':''} style="border:0;padding:0;margin:0"><div class="form-grid">${content}</div><button class="primary" type="submit">${label}</button></fieldset></form>`;}
function notify(message){$('#notice').textContent=message;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').textContent='',6500);}
function chart(key,label,unit){const h=state().history.slice(-240),vals=h.map(x=>x[key]),min=Math.min(0,...vals),max=Math.max(1,...vals),range=max-min;const points=h.map((x,i)=>`${42+i/Math.max(1,h.length-1)*640},${120-(x[key]-min)/range*95}`).join(' ');return `<svg class="plot" viewBox="0 0 700 150" role="img" aria-label="${label}; ${h.length} samples. Latest ${n(vals.at(-1)||0)} ${unit}."><path class="axis" d="M42 20V120H687"/><path class="axis" d="M42 70H687"/><text x="0" y="25">${n(max,0)}</text><text x="0" y="123">${n(min,0)}</text><polyline class="line" points="${points}"/><text x="42" y="144">${clock(h[0]?.time||0)}</text><text x="625" y="144">${clock(h.at(-1)?.time||0)}</text></svg><div class="plot-legend">${label}: ${n(vals.at(-1)||0)} ${unit}. Last ${h.length} samples at 15 s intervals. Full data available as CSV.</div>`;}
function inspector(){const s=state(),st=s.stages.find(x=>x.id===selected),loop=s.loops[st.id];return `<section class="card inspector" tabindex="0" aria-label="Selected equipment inspector"><div class="card-head"><span class="tag">${st.tag}</span>${badge(st.status)}</div><h2>${esc(st.name)}</h2><div class="inspector-focus">${action('Focus equipment','camera-focus')}</div><p style="font-size:12px">${esc(st.description)}</p><dl><dt>Rated model capacity</dt><dd>${n(st.capacityKgH/1000)} t/h</dd><dt>Current inlet throughput</dt><dd>${n(st.flowKgS*3.6)} t/h</dd><dt>Buffer inventory</dt><dd>${n(st.massKg)} / ${n(st.bufferKg,0)} kg</dd><dt>Base residence</dt><dd>${st.dwellS} s</dd><dt>Processed mass</dt><dd>${n(st.processedKg/1000,2)} t</dd><dt>Nominal motor load</dt><dd>${st.kW} kW</dd></dl>${form('speed',field('Equipment speed multiplier','value',st.speed,'type="number" min="0.5" max="1.2" step="0.05" required'),'Set speed',st.id)}${loop?`<hr class="rule"><h3>Temperature control</h3><dl><dt>Process truth</dt><dd>${n(loop.pv)} deg C</dd><dt>Sensor measurement</dt><dd>${n(loop.measured)} deg C</dd><dt>Controller output</dt><dd>${n(loop.output)} %</dd></dl>${form('setpoint',field('Setpoint (deg C)','value',loop.sp,`type="number" min="${st.id==='freeze'?-45:st.id==='fry'?155:60}" max="${st.id==='freeze'?-18:st.id==='fry'?195:95}" step="1" required`),'Set temperature',st.id)}`:''}<p class="status-text">Changing speed affects capacity and the residence of newly arriving material.</p></section>`;}
const modeButton=(name,id)=>`<button type="button" data-action="view-${id}" aria-pressed="${plantMode===id}">${name}</button>`;
function schematic(s){return `<div class="schematic" aria-label="Product flow schematic">${['Preparation','Thermal process','Cold chain'].map((area,i)=>`<section class="flow-area"><h3><span>0${i+1}</span> ${area}</h3><div class="flow-row">${s.stages.filter(st=>st.area===area).map(st=>`<button type="button" class="flow-unit ${selected===st.id?'selected':''}" data-unit="${st.id}" aria-label="Inspect ${st.name}" aria-pressed="${selected===st.id}"><span class="tag">${st.tag}</span>${equipmentSvg(st,playing&&!lens&&['RUNNING','DRAINING'].includes(s.mode))}<strong>${st.name}</strong><span class="flow">${n(st.flowKgS*3.6)} t/h</span><progress value="${Math.max(0,st.massKg)}" max="${st.bufferKg}" aria-label="${st.name} buffer inventory"></progress><small>${st.status}</small></button>`).join('')}</div></section>`).join('')}<p class="status-text">Product flows left to right through each row. Buffer bars show retained mass. ${recipeName(s.activeRecipe)}.</p></div>`;}
function assetRegister(s){return table(['Asset / operation','State','Flow','Buffer','Speed','Temperature'],s.stages.map((st,i)=>[`<button type="button" class="asset-link" data-unit="${st.id}" aria-label="Inspect ${st.name}" aria-pressed="${selected===st.id}"><span class="tag">${String(i+1).padStart(2,'0')} / ${st.tag}</span><strong>${esc(st.name)}</strong></button>`,badge(st.status),n(st.flowKgS*3.6)+' t/h',n(st.massKg)+' kg',n(st.speed,2)+'×',s.loops[st.id]?n(s.loops[st.id].pv)+' °C':'—']));}
function plantView(){const s=state(),m=summarise(s);return `<div class="plant-kpis">${metric('Packed output',n(m.outputKgH/1000),'t/h','Latest 15 s')}${metric('In process',n(Math.max(0,m.wipKg)/1000,2),'t','15 operations')}${metric('Finished product',n(m.productKg/1000,2),'t','All dispositions')}${metric('Electrical demand',n(s.utilities.powerKW,0),'kW','Model load')}</div><div class="plant-workspace"><section class="plant-panel"><div class="view-tabs" role="group" aria-label="Plant views">${modeButton('Plant model','model')}${modeButton('Flow schematic','flow')}${modeButton('Asset register','register')}</div>${plantMode==='model'?`<div class="viewer-toolbar"><div class="camera-actions" role="group" aria-label="Camera controls">${action('Fit','camera-fit')}${action('Plan','camera-plan')}${action('Orbit','camera-orbit')}<button type="button" data-action="camera-out" aria-label="Zoom out">−</button><button type="button" data-action="camera-in" aria-label="Zoom in">+</button></div><label>Overlay<select id="overlay">${options([['status','Equipment state'],['flow','Throughput'],['inventory','Buffer inventory'],['temperature','Temperature']].map(([id,name])=>({id,name})),overlay)}</select></label></div><div id="plant-canvas" class="plant-canvas" data-persistent="true"></div><div class="viewer-caption"><span>Illustrative layout · drag to orbit · select equipment</span><div><label><input id="show-labels" type="checkbox" ${showLabels?'checked':''}> Labels</label><label><input id="show-services" type="checkbox" ${showServices?'checked':''}> Services</label></div></div>`:plantMode==='flow'?schematic(s):assetRegister(s)}${graphicsFailed?'<p class="graphics-fallback" role="status">3D graphics are unavailable in this browser. The schematic and asset register remain fully operational.</p>':''}<div class="plant-trend"><div><h2>Packed output</h2><span>${n(m.outputKgH/1000)} t/h</span><small>Simulated time</small></div>${chart('outputKgH','Packed output','kg/h')}</div></section>${inspector()}</div><div class="plant-support grid equal">${card('Cold store & dispatch',`<dl><dt>Cold store temperature</dt><dd>${n(s.warehouse.tempC)} °C</dd><dt>Awaiting quality release</dt><dd>${n(m.pendingKg/1000,2)} t</dd><dt>Released stock</dt><dd>${n(m.releasedKg/1000,2)} t</dd><dt>Dispatched</dt><dd>${n(m.shippedKg/1000,2)} t</dd></dl><a href="#quality">Open quality & genealogy →</a>`)}${card('Start permissives',`<ul class="check-list">${permissives(s).map(x=>`<li><b class="${x.ok?'good':'bad'}">${x.ok?'READY':'WAIT'}</b><span>${x.reason}</span></li>`).join('')}</ul>`)}</div>${card('Material reconciliation',balance())}`;}

function balance(){const s=state(),m=summarise(s),a=assertPlant(s);return `<dl><dt>Raw potatoes fed</dt><dd>${n(m.rawFedKg)} kg</dd><dt>Water + oil + coating added</dt><dd>${n(s.ledger.waterAddedKg+s.ledger.oilAddedKg+s.ledger.coatAddedKg)} kg</dd><dt>In process + finished</dt><dd>${n(m.wipKg+m.productKg)} kg</dd><dt>Process by-product</dt><dd>${n(Object.values(s.ledger.waste).reduce((a,b)=>a+b,0))} kg</dd><dt>Water vapour</dt><dd>${n(m.vapourKg)} kg</dd><dt>Mass residual</dt><dd>${a.residualKg.toExponential(2)} kg</dd></dl><p class="status-text">Feed + additions = work in process + product + by-product + vapour. Raw stock and rejected receipts are accounted separately.</p>`;}
function controls(){const s=state();return `<div class="callout">Three PI loops share the material model. Sensor bias changes feedback; the process-truth value remains separately observable. This is an emulated controller, with no field connection.</div><div class="thirds">${Object.entries(s.loops).map(([id,l])=>card(s.stages.find(x=>x.id===id).name,`<dl><dt>Process truth</dt><dd>${n(l.pv)} deg C</dd><dt>Measured</dt><dd>${n(l.measured)} deg C</dd><dt>Output</dt><dd>${n(l.output)} %</dd><dt>Integral</dt><dd>${n(l.integral)}</dd></dl>${form('setpoint',field('Setpoint (deg C)','value',l.sp,`type="number" min="${id==='freeze'?-45:id==='fry'?155:60}" max="${id==='freeze'?-18:id==='fry'?195:95}" required`),'Apply setpoint',id)}${form('tune',field('Proportional gain','kp',l.kp,'type="number" min="0" max="20" step="0.1" required')+field('Integral gain per second','ki',l.ki,'type="number" min="0" max="1" step="0.005" required'),'Tune PI',id)}`)).join('')}</div>${card('Raw feed demand',form('feed',field('Requested raw feed (kg/h)','value',s.feedKgH,'type="number" min="1000" max="40000" step="1000" required'),'Apply feed'))}${card('Tag namespace',`<div class="actions">${action('Export tags CSV','csv-tags')}</div><label class="field search">Filter tags<input id="tag-filter" type="search" value="${esc(filter)}" placeholder="Tag, unit or quality"></label><div id="tag-table">${tagTable()}</div>`)}`;}
function tagTable(){const list=tags(state()).filter(t=>`${t.id} ${t.unit} ${t.quality}`.toLowerCase().includes(filter.toLowerCase()));return table(['Tag','Value','Unit','Quality','Sample time'],list.map(x=>[`<code>${x.id}</code>`,typeof x.value==='number'?n(x.value,2):esc(x.value),x.unit,badge(x.quality),clock(x.at)]));}
function production(){const s=state(),m=summarise(s);return `<div class="metrics">${metric('Raw stock',n(m.rawKg/1000),'t','Includes held stock')}${metric('Raw fed',n(m.rawFedKg/1000),'t','Actual campaign consumption')}${metric('Campaign yield',n(m.yield*100),'%','Finished / fed; transient until drained')}${metric('Model OEE',n(m.oee*100),'%','Definition below; not a plant KPI')}</div><div class="grid equal">${card('Recipe & campaign',form('selectRecipe',`<label class="field span2">Recipe<select name="id">${options(RECIPES,s.activeRecipe)}</select></label>`,'Select recipe')+`<p class="status-text">Recipe changes require a stopped, empty line. The first queued campaign adopts the selected recipe.</p>`+form('order',`<label class="field">Campaign recipe<select name="recipe">${options(RECIPES,s.activeRecipe)}</select></label>`+field('Raw allocation (kg)','rawKg',40000,'type="number" min="1000" max="200000" step="1000" required'),'Queue campaign'))}${card('Receive a synthetic raw lot',form('receive',field('Source label','source','Synthetic review lot','maxlength="100" required')+field('Net mass (kg)','kg',25000,'type="number" min="1000" max="50000" step="1000" required')+field('Dry matter (%)','dryMatter',21,'type="number" min="10" max="35" step="0.1" required')+field('Reducing sugar (%)','sugar',0.12,'type="number" min="0" max="2" step="0.01" required'),'Record receipt')+'<p class="status-text">Every new receipt starts on HOLD. Quality must approve it before intake.</p>')}</div>${card('Production orders',table(['Order / recipe','Raw target','Raw fed','Produced','State'],s.orders.map(x=>[`${x.id}<small>${recipeName(x.recipe)}</small>`,n(x.targetRawKg)+' kg',n(x.rawFedKg)+' kg',n(x.producedKg)+' kg',badge(x.status)])))}${card('Raw material inventory',rawTable())}${card('Performance calculation',`<dl><dt>Availability: running / planned seconds</dt><dd>${n(m.availability*100)} %</dd><dt>Performance: packed / ideal running output</dt><dd>${n(m.performance*100)} %</dd><dt>Quality: unaffected product / total product</dt><dd>${n(m.quality*100)} %</dd></dl><p>OEE = availability × performance × quality. Ideal packed rate is an illustrative 24,000 kg/h. Warm-up is counted in planned time; packaging residence makes the start-up KPI transient. Quality means no persistent hold, and does not replace release approval.</p>`)}`;}
function rawTable(){return table(['Raw lot / source','Stock','Sample','Grade','Quality actions'],state().rawLots.map(x=>[`${x.id}<small>${esc(x.source)}</small>`,n(x.kg)+' kg',`${n(x.dryMatter)} % dry<br>${n(x.sugar,2)} % sugar`,badge(x.grade),`<div class="actions">${x.grade==='HOLD'?button('Approve','approveRaw',x.id)+button('Reject','rejectRaw',x.id):''}${button('Recall','recall',x.id,'danger')}</div>`]));}
function quality(){const s=state(),m=summarise(s);return `<div class="metrics">${metric('Awaiting disposition',n(m.pendingKg/1000,2),'t','Sample, challenge and review required')}${metric('Released stock',n(m.releasedKg/1000,2),'t','Eligible only while cold chain remains valid')}${metric('Dispatched',n(m.shippedKg/1000,2),'t','Recorded synthetic shipments')}${metric('Cold store',n(s.warehouse.tempC),'deg C','Illustrative release threshold: -18 deg C')}</div><div class="callout">Release sequence: sample the finished lot, pass the detector challenge, then release. A persistent process hold cannot be cleared by acknowledging its alarm. Synthetic quality limits require site validation.</div><div class="actions section-space">${button('Run detector challenge','challenge')}${action('Export genealogy CSV','csv-genealogy')}</div><p class="status-text">Detector challenge: ${s.challenge.passed?`passed at ${clock(s.challenge.at)}; valid for 1 simulated hour`:'not yet performed'}.</p>${s.finishedLots.map(l=>card(`${l.id} / ${recipeName(l.recipe)}`,`<p class="status-text">${l.rawLotId} → ${l.orderId} → ${l.id}. Core maximum ${n(l.maxCoreC)} deg C.</p>${l.holdReasons.length?`<div class="callout alert">${l.holdReasons.map(esc).join('<br>')}</div>`:''}<dl><dt>Total produced</dt><dd>${n(l.totalKg)} kg</dd><dt>Pending / released</dt><dd>${n(l.pendingKg)} / ${n(l.releasedKg)} kg</dd><dt>Shipped / scrapped</dt><dd>${n(l.shippedKg)} / ${n(l.scrappedKg)} kg</dd><dt>Latest sample</dt><dd>${l.sample?`${l.sample.passed?'PASS':'FAIL'} / ${n(l.sample.coveredKg)} kg`:'Not sampled'}</dd><dt>Recall</dt><dd>${l.recalled?'ACTIVE':'None'}</dd></dl><div class="actions">${button('Sample lot','sample',l.id)}${button('Release lot','release',l.id,'primary')}${button('Reject pending stock','reject',l.id,'danger')}</div>${form('dispatch',field('Dispatch mass (kg)','kg',Math.min(100,Math.max(0,l.releasedKg)),'type="number" min="0.01" step="0.01" required'),'Record dispatch',l.id)}`)).join('')||card('Finished goods','<p>No finished lots yet. Load the Complete campaign scenario to review the full release and dispatch workflow.</p>')}${card('Raw quality & recall',rawTable())}${card('Shipments',table(['Shipment','Finished lot','Raw lot','Mass','Recall required'],s.shipments.map(x=>[x.id,x.lotId,x.rawLotId,n(x.kg)+' kg',x.recallRequired?'YES':'No'])))}`;}
function utilities(){const s=state(),u=s.utilities,w=s.ww,a=assertPlant(s);return `<div class="metrics">${metric('Fresh water used',n(u.waterUsedM3),'m3','Cumulative process use')}${metric('Electrical energy',n(u.electricKWh,0),'kWh','Integrated at one-second steps')}${metric('Thermal energy',n(u.thermalKWh,0),'kWh','Blancher and fryer demand')}${metric('Wastewater level',n(w.volumeM3),'m3',`Illustrative capacity ${w.capacityM3} m3`)}</div><div class="grid equal">${card('Water & wastewater balance',`<dl><dt>Fresh tank</dt><dd>${n(u.waterM3)} m3</dd><dt>Current wash / cleaning demand</dt><dd>${n(u.waterRateM3H)} m3/h</dd><dt>Fresh replenishment</dt><dd>${n(u.waterSupplyM3)} m3</dd><dt>Treated volume</dt><dd>${n(w.treatedM3)} m3</dd><dt>Non-product recovery</dt><dd>${n(w.recoveryM3)} m3</dd><dt>Discharge</dt><dd>${n(w.dischargeM3)} m3</dd><dt>Water residual</dt><dd>${a.waterResidualM3.toExponential(2)} m3</dd><dt>Wastewater residual</dt><dd>${a.wwResidualM3.toExponential(2)} m3</dd></dl>`)}${card('Treatment & energy',`<dl><dt>COD in equalisation</dt><dd>${n(w.codKg)} kg</dd><dt>COD removed</dt><dd>${n(w.codRemovedKg)} kg</dd><dt>COD discharged / recovered</dt><dd>${n(w.codOutKg)} kg</dd><dt>COD residual</dt><dd>${a.codResidualKg.toExponential(2)} kg</dd><dt>Model pH</dt><dd>${n(w.pHM,2)}</dd><dt>Steam pressure</dt><dd>${n(u.steamKPa)} kPa</dd><dt>Air pressure</dt><dd>${n(u.airKPa)} kPa</dd><dt>Refrigeration electricity</dt><dd>${n(u.refrigerationKWh)} kWh</dd></dl><p class="status-text">Treatment assumes 92% COD removal and 65% water recovery. These are study parameters, not EPA licence limits. Recovered water is not returned to food-contact service.</p>`)}${card('Wastewater inventory',chart('wwM3','Equalisation volume','m3'))}${card('Material balance',balance())}</div>`;}
function maintenance(){const s=state();return `<div class="grid equal">${card('Sanitation sequence',`${badge(s.clean.state)}<p>${esc(s.clean.reason)}</p><ol class="steps">${CLEAN_PHASES.map((p,i)=>`<li>${p.name} / ${p.durationS} s ${s.clean.state==='IN_PROGRESS'&&s.clean.phase===i?`<strong>ACTIVE ${s.clean.elapsed} s</strong>`:''}</li>`).join('')}</ol>${button('Start sanitation','clean','','primary')}<p class="status-text">Requires stopped, empty equipment and fryer temperature below 60 deg C. Wet-zone water cleaning is separate from fryer oil filtration and dry-zone inspection.</p>`)}${card('Consumables',`<dl>${[['oilKg','Fresh oil'],['coatKg','Coating ingredient'],['filmKg','Packaging film']].map(([k,l])=>`<dt>${l}</dt><dd>${n(s.stores[k])} kg</dd>`).join('')}</dl>${form('restock',`<label class="field">Consumable<select name="id"><option value="oilKg">Fresh oil</option><option value="coatKg">Coating ingredient</option><option value="filmKg">Packaging film</option></select></label>`+field('Restock mass (kg)','kg',1000,'type="number" min="1" max="20000" required'),'Record restock')}`)}</div>${card('Equipment intervention',table(['Asset','Running hours','Model wear','Isolation','Actions'],s.stages.map(x=>[`${x.tag}<small>${x.name}</small>`,n(x.runningS/3600,2),n(x.wear,3)+' %',x.isolated?'ISOLATED':'Released',`<div class="actions">${button(x.isolated?'Release isolation':'Isolate',x.isolated?'unisolate':'isolate',x.id)}${button('Inspect & repair','repair',x.id)}</div>`])))}${card('Maintenance record',table(['Work order','Equipment','Time','Result'],s.jobs.map(x=>[x.id,x.equipment,clock(x.at),x.action])))}${card('Sanitation record',table(['Time','Phase','Result'],s.clean.history.map(x=>[clock(x.at),x.phase,x.result])))}`;}
function alarms(){const s=state();return `${card('Alarm lifecycle',`<p class="status-text">Acknowledgement records operator response. Cause removal returns the alarm to normal. Trip reset is a separate command and never restarts the line.</p>${table(['Alarm / consequence','Priority','Condition','Raised','Action'],[...s.alarms].reverse().map(x=>[`${x.code}<small>${esc(x.message)}</small>`,badge(x.severity),x.active?'ACTIVE':'RETURNED',clock(x.firstAt),x.ackAt===null?button('Acknowledge','ack',x.id):`Ack ${clock(x.ackAt)}`]))}`)}<div class="grid equal">${card('Fryer process temperature',chart('fryC','Fryer process temperature','deg C'))}${card('Freezer process temperature',chart('freezeC','Freezer air temperature','deg C'))}</div><div class="actions">${action('Export historian CSV','csv-historian')}</div>${card('Event chronology',table(['Simulated time','Type','Event','Details'],[...s.events].reverse().slice(0,300).map(x=>[clock(x.at),x.kind,esc(x.message),`<code>${esc(JSON.stringify(x.details))}</code>`])))}<p class="status-text">Showing latest 300 events. The review export includes all retained events (maximum 3,000).</p>`;}
function integration(){const s=state();return `<div class="callout">Every interface here is emulated within the browser. No connection is made to Farm Frites, SAP, OPC UA, MQTT, a PLC or any operational network.</div><div class="grid equal">${card('Supervisory gateway',`${badge(s.faults.includes('comms-loss')?'STALE':'GOOD')}<p>Controller and physical-model time continue during a gateway outage. Tag samples freeze; supervisory commands are refused until restoration.</p><div class="actions">${button(s.faults.includes('comms-loss')?'Restore gateway':'Interrupt gateway',s.faults.includes('comms-loss')?'clearFault':'fault','comms-loss')}</div>`)}${card('ERP store-and-forward',`${badge(s.faults.includes('erp-offline')?'PENDING':'DELIVERED')}<p>Receipts, orders, lot creation, quality releases, dispatch and recalls create messages. Retry runs every 60 simulated seconds. Delivery is idempotent by message ID.</p><div class="actions">${button(s.faults.includes('erp-offline')?'Restore ERP':'Interrupt ERP',s.faults.includes('erp-offline')?'clearFault':'fault','erp-offline')}${button('Reconcile outbox','reconcile')}</div>`)}</div>${card('Message outbox',table(['Message','Event','Status','Attempts','Payload'],s.outbox.map(x=>[x.id,x.kind,badge(x.status),x.attempts,`<code>${esc(JSON.stringify(x.payload))}</code>`])))}${card('Read-only tag samples',tagTable())}`;}
function scenariosView(){const s=state();return `<div class="callout">Scenario loading replaces the current run after confirmation. Each preset is a deterministic command journal that can be exported, replayed and inspected. Playback speed changes wall-clock pacing only.</div><div class="thirds">${SCENARIOS.map(x=>`<button class="scenario" data-scenario="${x.id}"><strong>${x.name}</strong><span>${x.description}</span><small>Open at ${clock(x.until)} simulated time</small></button>`).join('')}</div><div class="section-space">${card('Fault injection bench',FAULTS.map(x=>`<div class="fault-row"><div><strong>${x.name}</strong> <small class="muted">${x.severity} / ${x.unit}</small><p>${x.effect}</p></div>${button(s.faults.includes(x.id)?'Remove cause':'Inject fault',s.faults.includes(x.id)?'clearFault':'fault',x.id,s.faults.includes(x.id)?'danger':'')}</div>`).join(''))}</div>${card('Time lens',`<p>Reconstruct an earlier state from the accepted command journal. The historical view is read-only and leaves the present unchanged.</p>${form('replay',field('Simulated second to inspect','until',Math.min(plant.time,900),`type="number" min="0" max="${plant.time}" step="1" required`),'Inspect earlier state')}<div class="actions">${action('Return to present','present')}</div>`)}`;}
function reference(){const s=state();return `<div class="callout">Independent engineering study by Sajeevan Veeriah, prepared for technical review. This is not an endorsed or calibrated Farm Frites Dooen digital twin. The real line arrangement, equipment, recipes and control specification have not been supplied.</div><div class="grid equal">${card('Review the demonstration',`<ol class="steps"><li>Open Scenario studio and load Steady production.</li><li>Select equipment in Process overview; compare throughput and buffer inventory.</li><li>Load Packaging bottleneck; remove the film-break cause and advance time.</li><li>Load Latched trip; remove the emergency-stop cause, reset, then explicitly resume.</li><li>Load Complete campaign; sample, challenge, release and dispatch from Quality.</li><li>Export the review JSON, run journal and historian CSV for analysis.</li></ol>`)}${card('Run & evidence',`<dl><dt>Model version</dt><dd>${VERSION}</dd><dt>Simulated time</dt><dd>${clock(s.time)}</dd><dt>Journal commands</dt><dd>${s.journal.length} / ${LIMITS.maxCommands}</dd><dt>Maximum run</dt><dd>24 simulated hours</dd><dt>Role</dt><dd>${s.role} (emulated)</dd></dl><div class="actions">${action('Export review JSON','export-review')}${action('Export replayable run','export-run')}${action('Import run','import')}${action('Save in this browser','save')}${action('Load saved run','load')}${action('Print this page','print')}</div>`)}</div>${card('Model assumptions',table(['Area','Declared model boundary'],ASSUMPTIONS.map(x=>x.map(esc))))}${card('Public references',table(['Source','Supports','Link'],SOURCES.map(x=>[esc(x.title),esc(x.supports),`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">Open source</a>`])))}${card('Recipe assumptions',table(['Recipe','Blanch','Fry','Freezer air','Freezing residence','Coating'],RECIPES.map(x=>[x.name,`${x.blanchC} deg C`,`${x.fryC} deg C`,`${x.freezeC} deg C`,`${x.freezeS} s`,`${n(x.coatFraction*100)} %`])))}${card('What the model does not establish','<p>Food safety, microbiological lethality, acrylamide formation, detailed heat transfer, electrical protection, functional safety, actual PLC code, site operating procedures and regulatory compliance are outside this uncalibrated study. Thermal responses and utility treatment are lumped models. Role selection is a teaching control, not authentication. The seed is preserved for reproducibility; the current engine has no stochastic disturbances.</p><p>Run data stays in memory unless explicitly saved or exported. Browser storage can be cleared by the browser. Exports are portable JSON and CSV; no external data is sent by the simulation.</p>')}`;}
const views={plant:plantView,control:controls,production,quality,utilities,maintenance,alarms,integration,scenarios:scenariosView,reference};
// Keep control nodes alive while the model ticks, so pointer/keyboard actions
// are not lost when their target is replaced during a live refresh.
function reconcileDOM(target,source){
 if(target.nodeType===3){if(target.nodeValue!==source.nodeValue)target.nodeValue=source.nodeValue;return;}
 if(target.nodeType===1&&target.hasAttribute('data-persistent')&&source.hasAttribute('data-persistent'))return;
 for(const a of [...target.attributes])if(!source.hasAttribute(a.name))target.removeAttribute(a.name);
 for(const a of source.attributes)if(target.getAttribute(a.name)!==a.value)target.setAttribute(a.name,a.value);
 const key=e=>e.nodeType===1?[e.tagName,e.id,e.dataset.cmd,e.dataset.id,e.dataset.action,e.dataset.unit,e.dataset.form].join('|'):'#text';
 const remaining=[...target.childNodes];
 for(const [i,child] of [...source.childNodes].entries()){
  let match=remaining.find(n=>key(n)===key(child));
  if(match){remaining.splice(remaining.indexOf(match),1);if(target.childNodes[i]!==match)target.insertBefore(match,target.childNodes[i]||null);reconcileDOM(match,child);}
  else target.insertBefore(child.cloneNode(true),target.childNodes[i]||null);
 }
 for(const child of remaining)child.remove();
 if(['INPUT','SELECT'].includes(target.tagName)&&document.activeElement!==target)target.value=source.value;
}
function paint(markup){const next=document.createElement('div');next.id='app';next.innerHTML=markup;reconcileDOM($('#app'),next);}
function recoveryHelp(s){
 if(s.mode==='TRIPPED'){
  const causes=FAULTS.filter(f=>s.faults.includes(f.id)&&f.severity==='TRIP'&&f.id!=='estop');
  const reset=commandStatus(s,'resetTrip');
  const roleHint=!['instructor','operator','engineer'].includes(s.role)?'<p>Select Operator, Engineer or Instructor under Role simulation to release and reset the E-stop.</p>':causes.length&&s.role!=='instructor'?'<p>Select Instructor under Role simulation to clear the separately injected trip causes.</p>':'';
  return `<section class="transport-help recovery" aria-label="Trip recovery"><strong>Trip recovery: release, reset, resume</strong>${roleHint}<p>${s.faults.includes('estop')?'1. Press Release E-stop in the control dock. Releasing it does not restart the line.':reset.enabled?'2. Press Reset trip in the control dock, then press Resume to restart.':'Reset is blocked. Resolve the causes below first.'}</p>${causes.map(f=>`<div class="recovery-cause"><span>${esc(f.name)}: ${esc(f.effect)}</span>${button('Clear simulated cause','clearFault',f.id)}</div>`).join('')}${s.loops.fry.pv>200?`<p>Fryer temperature is ${n(s.loops.fry.pv)} deg C; reset requires 200 deg C or below. Clear the temperature cause and use Play clock or +1 min to allow cooling.</p>`:''}${!reset.enabled&&!s.faults.includes('estop')&&!causes.length&&s.loops.fry.pv<=200?`<p>${esc(reset.reason)}</p>`:''}<p class="status-text">Material remains in the model. Existing quality holds remain recorded after recovery.</p></section>`;
 }
 if(s.mode==='HELD'){const resume=commandStatus(s,'resume');return `<div class="transport-help recovery"><strong>Line held.</strong> ${resume.enabled?'3. Press Resume in the control dock to restart the retained campaign.':`Resume unavailable: ${esc(resume.reason)}.`}</div>`;}
 return `<div class="transport-help">${s.mode==='STOPPED'&&!commandStatus(s,'start').enabled?`Start unavailable: ${esc(commandStatus(s,'start').reason)}. `:''}Stop retains the campaign and material. Drain empties the line. Clock playback is separate from plant motion.</div>`;
}
const dockObserver=new ResizeObserver(entries=>{for(const e of entries)document.documentElement.style.setProperty('--dock-height',e.target.offsetHeight+'px');});
const descriptions={plant:'Dooen process study / '+ 'Illustrative plant layout',control:'Controller loops, feed demand and the complete tag namespace.',production:'Recipes, campaigns and raw material receipts.',quality:'Sampling, release, recall and traceable dispatch.',utilities:'Water, energy and wastewater across the process.',maintenance:'Equipment isolation, consumables and sanitation.',alarms:'Alarm response and the process history behind it.',integration:'Emulated gateway, message delivery and reconciliation.',scenarios:'Controlled disturbances and replayable operating studies.',reference:'Model scope, assumptions and portable review evidence.'};
const navPaths=['M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z','M4 7h16M8 3v8M4 17h16M16 13v8','M4 5h16v16H4zM8 3v4M16 3v4M8 12h8M8 16h5','M12 3l8 3v6c0 5-8 9-8 9S4 17 4 12V6zM8 12l3 3 5-6','M12 3C9 8 5 12 5 16a7 7 0 0014 0c0-4-4-8-7-13z','M14 4l-2 5 3 3 5-2c2 7-5 10-9 6l-6 6-3-3 6-6C4 7 8 2 14 4z','M4 18h16l-2-3V9a6 6 0 00-12 0v6zM10 21h4','M3 5h6v6H3zM15 13h6v6h-6zM9 8h8v5','M5 4l15 8-15 8z','M5 3h14v18H5zM9 7h6M9 11h6M9 15h4'];
function render(){
 const s=state(),m=summarise(s),active=document.activeElement,focus=active?.id,focusKey=active?.dataset?.action?`[data-action="${active.dataset.action}"]`:active?.dataset?.cmd?`[data-cmd="${active.dataset.cmd}"]${active.dataset.id?`[data-id="${active.dataset.id}"]`:''}`:active?.dataset?.unit?`[data-unit="${active.dataset.unit}"]`:null,scroll=window.scrollY;
 paint(`<div class="shell"><aside class="rail"><a class="brand" href="#plant"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M4 23V9l12-6 12 6v14l-12 6zM4 9l12 7 12-7M16 16v13M10 6l12 7"/></svg><span>Open Industrial<small>Plant simulation</small></span></a><div class="nav-label">WORKSPACE</div><nav aria-label="Simulation workspaces">${routes.map(([id,name],i)=>`<a href="#${id}" aria-label="${name}" ${route===id?'aria-current="page"':''}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="${navPaths[i]}"/></svg><span>${name}</span>${id==='alarms'&&m.activeAlarms?`<b>${m.activeAlarms}</b>`:''}</a>`).join('')}</nav><div class="rail-bottom"><span class="study-dot"></span> Independent study<br><small>Dooen, Victoria<br>Illustrative geometry & synthetic data</small><a href="#reference">Model ${VERSION} ↗</a></div></aside><div class="main"><header class="top"><div class="breadcrumb">Potato processing <span>/</span> <strong>Dooen study</strong></div><div class="actions"><label for="role">Role simulation</label><select id="role">${options(['instructor','operator','engineer','quality','maintenance','reviewer'].map(id=>({id})),s.role)}</select>${action(document.body.dataset.theme==='dark'?'Light':'Dark','theme')}</div></header>${lens?`<div class="replay-bar"><strong>READ-ONLY TIME LENS / ${clock(lens.time)}</strong><span>Present is preserved at ${clock(plant.time)}.</span>${action('Return to present','present')}</div>`:''}<main id="workspace" class="workspace-${route}" tabindex="-1"><div class="heading"><div><h1>${routes.find(x=>x[0]===route)[1]}</h1><p>${descriptions[route]}</p></div><div class="actions">${action('Export run','export-run')}${action('Reset run','reset')}</div></div>${views[route]()}</main><footer class="footer"><span>Simulation only · ${m.activeAlarms} active alarms · ${m.unacknowledged} unacknowledged</span><span>1 s model resolution · ${s.journal.length} recorded commands</span></footer><div class="control-dock"><div class="transport" aria-label="Simulation transport"><div class="clock-controls"><span class="clock" aria-label="Simulated time">${clock(s.time)}</span><span class="clock-state">${playing?'Clock running':'Clock paused'}</span>${action(playing?'Pause clock':'Play clock','play')}${action('+1 min','step')}${action('+10 min','step-ten')}<label for="rate">Speed</label><select id="rate">${[1,10,30,60,120].map(x=>`<option value="${x}" ${x===rate?'selected':''}>${x}×</option>`).join('')}</select></div><div class="plant-controls">${badge(s.mode)}${button('Start','start','','primary')}${button('Stop','stop')}${button('Hold','hold')}${button('Resume','resume')}${button('Drain','drain')}${button('Reset trip','resetTrip')}${s.faults.includes('estop')?button('Release E-stop','releaseEstop','','danger'):button('E-stop','estop','','danger')}</div></div>${recoveryHelp(s)}</div></div></div>`);
 const host=$('#plant-canvas');
 if(spatial&&spatial.host!==host){spatial.dispose();spatial=null;}
 if(host&&!spatial){if(graphicsFailed){plantMode='flow';queueMicrotask(render);}else spatial=new SpatialPlant(host,id=>{selected=id;render();},()=>{graphicsFailed=true;plantMode='flow';queueMicrotask(render);});}
 spatial?.update(s,selected,playing&&!lens,rate,{overlay,labels:showLabels,services:showServices,dark:document.body.dataset.theme==='dark'});
 const dock=$('.control-dock');if(dock){dockObserver.disconnect();dockObserver.observe(dock);document.documentElement.style.setProperty('--dock-height',dock.offsetHeight+'px');}
 if(focus)document.getElementById(focus)?.focus({preventScroll:true});else if(focusKey)document.querySelector(focusKey)?.focus({preventScroll:true});if(window.scrollY!==scroll)window.scrollTo(0,scroll);
}

function runCommand(cmd,p={}){if(lens){notify('Return to the present before issuing commands.');return;}try{const r=act(plant,cmd,p);if(r.ok&&['start','resume','drain','clean'].includes(cmd))playing=true;notify(r.reason);assertPlant(plant);render();}catch(e){playing=false;notify(`Model stopped: ${e.message}`);console.error(e);}}
function step(seconds){if(lens){notify('The time lens is read-only. Return to present to advance.');return;}try{const available=LIMITS.maxSeconds-plant.time;advance(plant,Math.min(seconds,available));assertPlant(plant);if(seconds>=available){playing=false;notify('24-hour run boundary reached. Export and reset to continue.');}render();}catch(e){playing=false;notify(e.message);console.error(e);}}
function saveFile(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function download(kind){const s=state(),prefix=`Potato-Simulation-${clock(s.time).replaceAll(':','-')}`;if(kind==='run')saveFile(prefix+'-Run.json',exportRun(s),'application/json');else if(kind==='review')saveFile(prefix+'-Review.json',JSON.stringify(review(s),null,2),'application/json');else saveFile(prefix+'-'+kind+'.csv',csv(s,kind),'text/csv;charset=utf-8');notify('Export generated from the current visible simulation state.');}
function replaceWith(fn){playing=false;pending=fn;$('#replace-dialog').showModal();}
$('#cancel-replace').addEventListener('click',()=>{pending=null;$('#replace-dialog').close();});
$('#confirm-replace').addEventListener('click',()=>{try{const candidate=pending();assertPlant(candidate);plant=candidate;lens=null;render();notify('Run loaded. The simulation clock is paused.');}catch(e){notify(`Run not replaced: ${e.message}`);}pending=null;$('#replace-dialog').close();});
$('#replace-dialog').addEventListener('cancel',()=>pending=null);
$('#app').addEventListener('click',e=>{const target=e.target.closest('button');if(!target)return;if(target.dataset.cmd){runCommand(target.dataset.cmd,target.dataset.id?{id:target.dataset.id}:{});return;}if(target.dataset.unit){selected=target.dataset.unit;render();if(matchMedia('(max-width:900px)').matches)document.querySelector('.inspector')?.scrollIntoView({block:'start'});return;}if(target.dataset.scenario){replaceWith(()=>scenario(target.dataset.scenario));return;}const a=target.dataset.action;if(a?.startsWith('view-')){plantMode=a.slice(5);render();return;}if(a?.startsWith('camera-')){if(plantMode!=='model'){plantMode='model';render();}spatial?.command(a.slice(7));return;}switch(a){case 'play':if(lens)return notify('Return to present to run the clock.');playing=!playing;render();break;case 'step':step(60);break;case 'step-ten':step(600);break;case 'theme':document.body.dataset.theme=document.body.dataset.theme==='dark'?'light':'dark';render();break;case 'reset':replaceWith(()=>createPlant());break;case 'present':lens=null;render();break;case 'export-run':download('run');break;case 'export-review':download('review');break;case 'csv-historian':download('historian');break;case 'csv-tags':download('tags');break;case 'csv-genealogy':download('genealogy');break;case 'save':try{localStorage.setItem('potato-sim-run-v1',exportRun(plant));notify('Present run saved in this browser.');}catch(err){notify(`Save failed: ${err.message}. Use Export run instead.`);}break;case 'load':try{const text=localStorage.getItem('potato-sim-run-v1');if(!text)return notify('No saved run in this browser.');const candidate=importRun(text);assertPlant(candidate);replaceWith(()=>candidate);}catch(err){notify(err.message);}break;case 'import':$('#import-file').click();break;case 'print':window.print();break;}});
$('#app').addEventListener('submit',e=>{const f=e.target.closest('form');if(!f)return;e.preventDefault();const payload=Object.fromEntries(new FormData(f));for(const key of ['value','kp','ki','kg','dryMatter','sugar','rawKg','until'])if(key in payload)payload[key]=Number(payload[key]);if(f.dataset.id)payload.id=f.dataset.id;if(f.dataset.form==='replay'){playing=false;try{lens=replayRun(JSON.parse(exportRun(plant)),payload.until);render();notify('Historical view opened. The present run is preserved.');}catch(err){notify(err.message);}return;}runCommand(f.dataset.form,payload);});
$('#app').addEventListener('change',e=>{if(e.target.id==='role')runCommand('role',{id:e.target.value});if(e.target.id==='rate'){rate=Number(e.target.value);render();}if(e.target.id==='overlay'){overlay=e.target.value;render();}if(e.target.id==='show-labels'){showLabels=e.target.checked;render();}if(e.target.id==='show-services'){showServices=e.target.checked;render();}});
$('#app').addEventListener('input',e=>{if(e.target.id==='tag-filter'){filter=e.target.value;$('#tag-table').innerHTML=tagTable();}});
$('#import-file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>LIMITS.maxImportBytes)throw Error('File exceeds the 1.5 MB run limit');const text=await f.text();const candidate=importRun(text);assertPlant(candidate);replaceWith(()=>candidate);}catch(err){notify(`Import failed: ${err.message}`);}e.target.value='';});
function routeChanged(){const id=location.hash.slice(1);if(id==='workspace')return;const next=routes.some(x=>x[0]===id)?id:'plant',changed=next!==route;route=next;filter='';render();if(changed){window.scrollTo(0,0);$('#workspace')?.focus({preventScroll:true});}}
window.addEventListener('hashchange',routeChanged);
setInterval(()=>{if(!playing||lens||$('#replace-dialog').open)return;try{const available=LIMITS.maxSeconds-plant.time;advance(plant,Math.min(rate,available));assertPlant(plant);if(available<=rate){playing=false;notify('24-hour run boundary reached. Export this run before resetting.');}if(!['INPUT','SELECT'].includes(document.activeElement?.tagName))render();}catch(e){playing=false;notify(`Model stopped: ${e.message}`);console.error(e);}},1000);
routeChanged();

if ('serviceWorker' in navigator) navigator.serviceWorker.addEventListener('message',event=>{if(event.data?.type==='POTATO_VERSION_REQUEST')event.ports[0]?.postMessage('potato-spatial-7');});
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js', {updateViaCache:'none'}).then(r=>r.update()).catch(()=>{});
