import test from 'node:test';
import assert from 'node:assert/strict';
import {createPlant,scenario,act,advance,assertPlant,exportRun,importRun} from '../simulator/engine.mjs';
import {GATES} from '../simulator/systems.mjs';
const sys=(s,op,id='',extra={})=>act(s,'system',{op,id,...extra});
test('all 90 wires have unique addresses and traceable cabinet terminals',()=>{const s=createPlant(),w=s.systems.wires;assert.equal(w.length,90);assert.equal(new Set(w.map(a=>a.id)).size,90);assert.equal(new Set(w.map(a=>a.address)).size,90);for(const a of w)assert(s.systems.cabinets.some(c=>c.id===a.cabinet));});
test('photoeye circuit stops packing and repaired circuit restores flow without losing mass',()=>{const s=scenario('baseline'),w=s.systems.wires.find(w=>w.stage==='pack'&&w.signal==='PE');assert(sys(s,'wire',w.id).ok);advance(s,60);assert.equal(s.stages.find(a=>a.id==='pack').flowKgS,0);assert(s.alarms.some(a=>a.code===w.cabinet&&a.active));assert(sys(s,'wire',w.id).ok);advance(s,60);assert(s.stages.find(a=>a.id==='pack').flowKgS>0);assertPlant(s);});
test('cabinet breaker and overload remove outputs independently',()=>{const s=scenario('baseline'),c=s.systems.cabinets[0];sys(s,'breaker',c.id);advance(s,1);assert.equal(c.volts,0);assert.equal(s.systems.io.intake.output,false);sys(s,'overload',c.id);sys(s,'breaker',c.id);assert.equal(c.volts,24);assert.equal(s.systems.io.intake.output,false);sys(s,'overload',c.id);assert.equal(s.systems.io.intake.output,true);});
test('PLC stop and I/O network stop motion, restoration preserves the campaign',()=>{const s=scenario('baseline'),raw=s.ledger.rawFedKg;sys(s,'plc');advance(s,20);assert.equal(s.ledger.rawFedKg,raw);sys(s,'plc');sys(s,'network','REMOTE-IO');advance(s,10);assert.equal(s.ledger.rawFedKg,raw);sys(s,'network','REMOTE-IO');advance(s,10);assert(s.ledger.rawFedKg>raw);assertPlant(s);});
test('ten PLC scans per process second and latency watchdog blocks output',()=>{const s=createPlant();advance(s,2);assert.equal(s.systems.scans,20);sys(s,'latency','',{value:600});assert(s.systems.watchdog);sys(s,'latency','',{value:20});assert(!s.systems.watchdog);});
test('robot gripper fault requires cause removal, held state and manual robot reset',()=>{const s=scenario('baseline');sys(s,'robotFault','case');advance(s,10);assert.equal(s.stages.find(a=>a.id==='pack').flowKgS,0);assert(!sys(s,'robotReset','case').ok);sys(s,'robotFault','case');assert(!sys(s,'robotReset','case').ok);act(s,'hold');assert(sys(s,'robotReset','case').ok);assert.equal(s.mode,'HELD');act(s,'resume');advance(s,60);assert(s.stages.find(a=>a.id==='pack').flowKgS>0);});
test('robot cycle rate constrains process capacity',()=>{const s=scenario('baseline');act(s,'hold');assert(sys(s,'robotRate','case',{value:20}).ok);act(s,'resume');advance(s,60);assert(s.stages.find(a=>a.id==='pack').flowKgS<=1+1e-8);assertPlant(s);});
test('warehouse missions reserve one aisle and E-stop freezes travel',()=>{const s=scenario('baseline');advance(s,100);assert(s.systems.warehouse.missions.length>0);assert(s.systems.warehouse.amrs.filter(a=>a.status==='MOVING').length<=1);act(s,'estop');const before=JSON.stringify(s.systems.warehouse.amrs);advance(s,5);assert.equal(JSON.stringify(s.systems.warehouse.amrs),before);});
test('purchase receipt is idempotent and joins raw stock conservation in quality hold',()=>{const s=createPlant();assert(sys(s,'purchase','',{kg:10000,price:0.3}).ok);const p=s.systems.purchases[0];assert(sys(s,'receivePO',p.id).ok);assert(!sys(s,'receivePO',p.id).ok);assert.equal(s.rawLots.at(-1).grade,'HOLD');assert.equal(s.rawLots.at(-1).source,p.id);assertPlant(s);});
test('sales cannot reserve unproduced stock or invoice undispatched material',()=>{const s=createPlant();sys(s,'sales','',{kg:600,price:2});const o=s.systems.sales[0];assert(!sys(s,'reserve',o.id).ok);assert(!sys(s,'invoice',o.id).ok);});
test('work-order closure requires isolation and consumes exactly one spare',()=>{const s=createPlant();sys(s,'workOrder','pack');const w=s.systems.workOrders[0];assert(!sys(s,'completeWork',w.id).ok);act(s,'isolate',{id:'pack'});assert(sys(s,'completeWork',w.id).ok);assert(!sys(s,'completeWork',w.id).ok);assert.equal(s.systems.spares,9);assert(s.stages.find(a=>a.id==='pack').isolated);});
test('lifecycle gates require evidence and predecessors; change reopens every gate',()=>{const s=createPlant();assert(!sys(s,'gate','commercial').ok);sys(s,'evidence','site',{note:'Illustrative site review'});assert(!sys(s,'gate','site').ok);for(const [id] of GATES){assert(sys(s,'evidence',id,{note:'Synthetic engineering review evidence'}).ok);assert(sys(s,'gate',id).ok);}sys(s,'change','',{note:'Increase design throughput'});assert(s.systems.gates.every(g=>g.status==='OPEN'));assert.equal(s.systems.evidence.length,0);});
test('supervisory outage preserves PLC operation; historian outage stops samples',()=>{const s=scenario('baseline');sys(s,'network','SCADA');assert(!act(s,'hold').ok);assert(act(s,'estop').ok);sys(s,'network','SCADA');act(s,'releaseEstop');act(s,'resetTrip');act(s,'resume');sys(s,'network','HISTORIAN');const count=s.history.length;advance(s,30);assert.equal(s.history.length,count);sys(s,'network','HISTORIAN');advance(s,15);assert(s.history.length>count);});
test('new network domains defer ERP messages and reconcile idempotently',()=>{const s=createPlant();sys(s,'network','DMZ');act(s,'order',{recipe:'straight',rawKg:1000});assert.equal(s.outbox.at(-1).status,'PENDING');sys(s,'network','DMZ');act(s,'reconcile');assert.equal(s.outbox.at(-1).status,'DELIVERED');const count=s.delivered.length;act(s,'reconcile');assert.equal(s.delivered.length,count);});
test('systems commands validate nonfinite values, roles and replay exactly',()=>{const s=createPlant();assert(!sys(s,'latency','',{value:NaN}).ok);sys(s,'purchase','',{kg:1000,price:0.3});sys(s,'wire','W1-2');advance(s,3);assert.deepEqual(importRun(exportRun(s)),s);act(s,'role',{id:'reviewer'});assert(!sys(s,'plc').ok);});

test('cell gate opening latches robot and closing it does not reset',()=>{const s=scenario('baseline');sys(s,'robotGate','case');advance(s,1);assert.equal(s.stages.find(a=>a.id==='pack').flowKgS,0);assert(s.systems.robots[0].latched);act(s,'hold');assert(!sys(s,'robotReset','case').ok);sys(s,'robotGate','case');assert(s.systems.robots[0].latched);assert(sys(s,'robotReset','case').ok);assertPlant(s);});

test('sales planning creates exactly one linked production campaign',()=>{const s=createPlant();sys(s,'sales','',{kg:7000,price:2});const o=s.systems.sales[0];assert(sys(s,'planSales',o.id).ok);assert(!sys(s,'planSales',o.id).ok);const campaign=s.orders.find(c=>c.id===o.campaignId);assert.equal(campaign.targetRawKg,10000);assert.equal(campaign.status,'QUEUED');});
