import {cp,mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const target=resolve('dist');
await rm(target,{recursive:true,force:true});
await mkdir(target,{recursive:true});
await cp(resolve('simulator'),target,{recursive:true});
await cp(resolve('simulator'),resolve(target,'potato'),{recursive:true});
await cp(resolve('web'),resolve(target,'suite'),{recursive:true});
await writeFile(resolve(target,'.nojekyll'),'\n','utf8');
console.log('Built potato plant digital twin at dist/ and dist/potato/; legacy suite at dist/suite/.');
