import assert from 'node:assert/strict';
import {FAULTS} from '../simulator/catalog.mjs';
import {importRun} from '../simulator/engine.mjs';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve,extname,sep} from 'node:path';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? pathToFileURL(resolve(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright/index.mjs')).href : 'playwright');
let server;
const root=resolve('dist');
const base=process.env.OIA_BASE_URL?.replace(/\/$/,'')||'http://127.0.0.1:4185';
if(!process.env.OIA_BASE_URL){server=createServer(async(req,res)=>{try{const path=decodeURIComponent(new URL(req.url,base).pathname);const file=resolve(root,'.'+path+(path.endsWith('/')?'index.html':''));if(!file.startsWith(root+sep))throw Error();const mime={'.html':'text/html','.mjs':'text/javascript','.js':'text/javascript','.css':'text/css'};res.setHeader('Content-Type',mime[extname(file)]||'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404);res.end('Not found');}});await new Promise(r=>server.listen(4185,'127.0.0.1',r));}
let browser;
try{
 browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000},bypassCSP:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 async function openRoute(name){await page.getByRole('link',{name,exact:true}).click();await page.getByRole('heading',{name,exact:true}).waitFor({state:'visible'});}
 await page.goto(base+'/');await page.getByRole('heading',{name:'Process overview',exact:true}).waitFor();
 await page.locator('#plant-canvas [role="img"]').waitFor({state:'visible'});
 assert.equal(await page.locator('.asset-pin').count(),15);
 // Spatial controls must change the visible camera and preserve asset selection.
 await page.getByRole('button',{name:'Plan',exact:true}).click();assert.match(await page.locator('#plant-canvas').getAttribute('data-camera'),/^plan:/);
 await page.getByRole('button',{name:'Orbit',exact:true}).click();assert.match(await page.locator('#plant-canvas').getAttribute('data-camera'),/^orbit:/);
 await page.getByRole('button',{name:'Zoom in',exact:true}).click();assert.match(await page.locator('#plant-canvas').getAttribute('data-camera'),/:1.25:/);
 await page.getByRole('button',{name:'Zoom out',exact:true}).click();assert.match(await page.locator('#plant-canvas').getAttribute('data-camera'),/:1.00:/);
 await page.locator('[data-unit="freeze"]').click();await page.getByRole('button',{name:'Focus equipment',exact:true}).click();assert.match(await page.locator('#plant-canvas').getAttribute('data-camera'),/:2.50:freeze$/);
 await page.getByRole('button',{name:'Fit',exact:true}).click();
 await page.getByRole('combobox',{name:'Overlay',exact:true}).selectOption('temperature');assert.match(await page.locator('[data-unit="freeze"] small').innerText(),/°C/);
 await page.getByRole('combobox',{name:'Overlay',exact:true}).selectOption('inventory');assert.match(await page.locator('[data-unit="freeze"] small').innerText(),/% buffer/);
 await page.getByRole('combobox',{name:'Overlay',exact:true}).selectOption('flow');assert.match(await page.locator('[data-unit="freeze"] small').innerText(),/t\/h/);
 await page.getByLabel('Labels',{exact:true}).uncheck();assert.equal(await page.locator('.asset-pin.details').count(),0);await page.getByLabel('Labels',{exact:true}).check();
 await page.getByLabel('Services',{exact:true}).uncheck();assert.equal(await page.getByLabel('Services',{exact:true}).isChecked(),false);await page.getByLabel('Services',{exact:true}).check();
 for(const mode of ['Flow schematic','Asset register','Plant model']){await page.getByRole('button',{name:mode,exact:true}).click();assert.equal(await page.getByRole('button',{name:/^Inspect /}).count(),15);assert.equal(await page.locator('[data-unit="freeze"]').getAttribute('aria-pressed'),'true');await page.locator('[data-unit="fry"]').click();assert.equal(await page.locator('.inspector h2').innerText(),'Par-fry');await page.locator('[data-unit="freeze"]').click();}
 await page.getByRole('combobox',{name:'Overlay',exact:true}).selectOption('status');
 assert.equal(await page.getByRole('link',{name:'Open original OIA suite'}).count(),0);
 const routes=['Process overview','Control & I/O','Production & intake','Quality & genealogy','Utilities & environment','Maintenance & sanitation','Alarms & historian','Integration lab','Scenario studio','Engineering reference'];
 for(const name of routes){await openRoute(name);await page.getByRole('heading',{name,exact:true}).waitFor();assert.equal(await page.locator('body').evaluate(e=>e.scrollWidth>innerWidth),false,name+' overflow');}
 async function pauseClock(){if(await page.getByRole('button',{name:'Pause clock',exact:true}).count())await page.getByRole('button',{name:'Pause clock',exact:true}).click();}
 async function exported(){const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export run',exact:true}).click();return importRun(await readFile(await(await pending).path(),'utf8'));}
 async function click(label){await page.getByRole('button',{name:label,exact:true}).click();}
 async function submit(type,values,id){const f=page.locator(`form[data-form="${type}"]${id?`[data-id="${id}"]`:''}`);for(const [key,value] of Object.entries(values)){const input=f.locator(`[name="${key}"]`);if(await input.evaluate(e=>e.tagName)==='SELECT')await input.selectOption(String(value));else await input.fill(String(value));}await f.getByRole('button').click();}
 // The entry path itself must support Start -> motion -> Stop -> restart.
 await openRoute('Process overview');assert.equal(await page.getByRole('button',{name:'Start',exact:true}).isEnabled(),true);assert.equal(await page.getByRole('button',{name:'Stop',exact:true}).isEnabled(),false);
 const initial=await exported();await click('Start');await page.waitForFunction(()=>document.querySelector('.clock').textContent!=='00:40:00');await pauseClock();const running=await exported();assert.ok(running.time>initial.time);assert.ok(running.ledger.rawFedKg>initial.ledger.rawFedKg);
 await click('Stop');const stopped=await exported();assert.equal(stopped.mode,'STOPPED');assert.ok(stopped.stages.every(x=>x.flowKgS===0));await click('+1 min');assert.equal((await exported()).ledger.rawFedKg,stopped.ledger.rawFedKg);
 await click('Start');await pauseClock();await click('+10 min');assert.equal((await exported()).activeOrderId,initial.activeOrderId);
 async function preset(name){await openRoute('Scenario studio');await page.getByRole('button',{name:new RegExp('^'+name+' ')}).click();await page.getByRole('button',{name:'Replace run',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});}
 await preset('Steady production');await openRoute('Process overview');assert.equal(await page.getByRole('button',{name:/^Inspect /}).count(),15);
 await page.getByRole('button',{name:'Hold',exact:true}).click();assert.match(await page.locator('.transport').innerText(),/HELD/);await page.getByRole('button',{name:'Resume',exact:true}).click();assert.match(await page.locator('.transport').innerText(),/RUNNING/);
 await page.getByRole('button',{name:'E-stop',exact:true}).click();assert.match(await page.locator('.transport').innerText(),/TRIPPED/);assert.equal(await page.getByRole('button',{name:'Reset trip',exact:true}).isEnabled(),false);assert.match(await page.getByRole('button',{name:'Reset trip',exact:true}).getAttribute('title'),/Remove every trip cause/);
 await click('Release E-stop');assert.equal((await exported()).mode,'TRIPPED');assert.match(await page.locator('.recovery').innerText(),/Press Reset trip/);await click('Reset trip');assert.equal((await exported()).mode,'HELD');assert.match(await page.locator('.recovery').innerText(),/Press Resume/);await click('Resume');await pauseClock();await click('+1 min');assert.equal((await exported()).mode,'RUNNING');
 for(const [width,role] of [[390,'operator'],[768,'engineer'],[1440,'instructor']]){await page.setViewportSize({width,height:1000});await page.getByRole('combobox',{name:'Role simulation'}).selectOption(role);await click('E-stop');await click('Release E-stop');assert.equal((await exported()).mode,'TRIPPED');await click('Reset trip');await click('Resume');await pauseClock();await click('+1 min');assert.equal((await exported()).mode,'RUNNING');assert.equal(new URL(page.url()).hash,'#plant');}
 // Releasing E-stop must not erase another active trip. Recovery stays on this screen.
 await page.getByRole('combobox',{name:'Role simulation'}).selectOption('instructor');await openRoute('Scenario studio');await page.locator('[data-cmd="fault"][data-id="power-loss"]').click();await openRoute('Process overview');await click('E-stop');await click('Release E-stop');assert.equal(await page.getByRole('button',{name:'Reset trip',exact:true}).isEnabled(),false);assert.match(await page.locator('.recovery').innerText(),/Electrical supply loss/);await page.locator('.recovery [data-cmd="clearFault"][data-id="power-loss"]').click();await click('Reset trip');await click('Resume');await pauseClock();
 await preset('Complete campaign');await openRoute('Quality & genealogy');await page.getByRole('button',{name:'Sample lot',exact:true}).click();await page.getByRole('button',{name:'Run detector challenge',exact:true}).click();await page.getByRole('button',{name:'Release lot',exact:true}).click();await page.getByLabel('Dispatch mass (kg)').fill('100');await page.getByRole('button',{name:'Record dispatch',exact:true}).click();assert.match(await page.locator('main').innerText(),/SIM-SHIP-1/);
 const shippedModel=await exported();await page.locator(`[data-cmd="recall"][data-id="${shippedModel.shipments[0].rawLotId}"]`).click();assert.equal((await exported()).shipments[0].recallRequired,true);await click('Reject pending stock');assert.ok((await exported()).finishedLots[0].scrappedKg>0);
 await openRoute('Control & I/O');await page.getByLabel('Filter tags').fill('FRY-901.TT');assert.equal(await page.locator('#tag-table tbody tr').count(),3);
 await openRoute('Scenario studio');await page.getByLabel('Simulated second to inspect').fill('900');await page.getByRole('button',{name:'Inspect earlier state',exact:true}).click();assert.match(await page.locator('.replay-bar').innerText(),/READ-ONLY/);assert.equal(await page.getByRole('button',{name:'Start',exact:true}).isEnabled(),false);await page.locator('.replay-bar').getByRole('button',{name:'Return to present'}).click();
 await openRoute('Engineering reference');await page.getByRole('button',{name:'Save in this browser'}).click();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export replayable run'}).click();const download=await downloadPromise;assert.match(download.suggestedFilename(),/Run.json$/);
 await page.getByRole('combobox',{name:'Role simulation'}).selectOption('reviewer');assert.equal(await page.getByRole('button',{name:'Start',exact:true}).isEnabled(),false);assert.match(await page.getByRole('button',{name:'Start',exact:true}).getAttribute('title'),/reviewer.*cannot/);await page.getByRole('combobox',{name:'Role simulation'}).selectOption('instructor');
 // Exercise every equipment inspector, then change and read back actual model controls.
 await preset('Steady production');await openRoute('Process overview');
 for(const unit of await page.locator('[data-unit]').evaluateAll(es=>es.map(e=>({id:e.dataset.unit,name:e.querySelector('strong').textContent})))){await page.locator(`[data-unit="${unit.id}"]`).click();assert.equal(await page.locator('.inspector h2').innerText(),unit.name);}
 await submit('speed',{value:0.8},'pallet');assert.equal((await exported()).stages.find(x=>x.id==='pallet').speed,0.8);
 await openRoute('Control & I/O');await submit('feed',{value:25000});await submit('setpoint',{value:180},'fry');await submit('tune',{kp:2,ki:0.05},'fry');let model=await exported();assert.equal(model.feedKgH,25000);assert.equal(model.loops.fry.sp,180);assert.equal(model.loops.fry.kp,2);
 await openRoute('Integration lab');await click('Interrupt gateway');assert.equal(await page.getByRole('button',{name:'Hold',exact:true}).isEnabled(),false);await click('+1 min');await click('Restore gateway');await click('Interrupt ERP');
 await openRoute('Production & intake');await submit('receive',{source:'Browser verified receipt',kg:5000,dryMatter:21,sugar:0.12});model=await exported();const received=model.rawLots.at(-1).id;assert.equal(model.rawLots.at(-1).grade,'HOLD');assert.ok(model.outbox.some(x=>x.status==='PENDING'));
 await page.locator(`[data-cmd="approveRaw"][data-id="${received}"]`).click();assert.equal((await exported()).rawLots.at(-1).grade,'RELEASED');
 await submit('receive',{source:'Browser rejected receipt',kg:5000,dryMatter:15,sugar:1});model=await exported();const rejected=model.rawLots.at(-1).id;assert.equal(await page.locator(`[data-cmd="approveRaw"][data-id="${rejected}"]`).isEnabled(),false);await page.locator(`[data-cmd="rejectRaw"][data-id="${rejected}"]`).click();assert.equal((await exported()).rawLots.at(-1).kg,0);
 await submit('order',{recipe:model.activeRecipe,rawKg:5000});assert.equal((await exported()).orders.at(-1).targetRawKg,5000);
 await openRoute('Integration lab');await click('Restore ERP');await click('Reconcile outbox');assert.ok((await exported()).outbox.every(x=>x.status==='DELIVERED'));
 await click('Stop');await openRoute('Maintenance & sanitation');await page.locator('[data-cmd="isolate"][data-id="pack"]').click();await page.locator('[data-cmd="repair"][data-id="pack"]').click();await page.locator('[data-cmd="unisolate"][data-id="pack"]').click();model=await exported();assert.ok(model.jobs.some(x=>x.equipment==='pack'));const oil=model.stores.oilKg;await submit('restock',{id:'oilKg',kg:1000});assert.equal((await exported()).stores.oilKg,oil+1000);
 await preset('Cold start');await openRoute('Production & intake');await submit('selectRecipe',{id:'wedges'});assert.equal((await exported()).activeRecipe,'wedges');
 await openRoute('Maintenance & sanitation');await click('Start sanitation');await pauseClock();await click('Stop');assert.equal((await exported()).clean.state,'DIRTY');await click('Start sanitation');await pauseClock();await click('+10 min');await click('+10 min');assert.equal((await exported()).clean.state,'CLEAN');
 await click('Start');await pauseClock();await click('Hold');await click('Resume');await pauseClock();assert.equal((await exported()).mode,'STARTING');await click('+10 min');await click('+10 min');
 await click('Drain');await pauseClock();const drainFed=(await exported()).ledger.rawFedKg;await click('Hold');await click('Resume');await pauseClock();for(let i=0;i<12;i++)await click('+10 min');model=await exported();assert.equal(model.mode,'STOPPED');assert.equal(model.ledger.rawFedKg,drainFed);
 // Every fault button must inject and remove its intended model cause.
 for(const fault of FAULTS){await preset('Cold start');await page.locator(`[data-cmd="fault"][data-id="${fault.id}"]`).click();assert.ok((await exported()).faults.includes(fault.id));await openRoute('Alarms & historian');const ack=page.locator('[data-cmd="ack"]').first();if(await ack.count()){if(fault.id==='comms-loss'){assert.equal(await ack.isEnabled(),false);assert.match(await ack.getAttribute('title'),/gateway is unavailable/);}else{await ack.click();assert.ok((await exported()).alarms.some(x=>x.ackAt!==null));}}await openRoute('Scenario studio');await page.locator(`.fault-row [data-cmd="clearFault"][data-id="${fault.id}"]`).click();assert.equal((await exported()).faults.includes(fault.id),false);}
 await click('+1 min');
 // Saved run and import paths are checked through exported user-visible data.
 await openRoute('Engineering reference');await click('Save in this browser');const saved=await exported();await click('Reset run');await click('Keep current run');assert.equal((await exported()).time,saved.time);await click('Reset run');await click('Replace run');assert.equal((await exported()).time,0);await click('Load saved run');await click('Replace run');assert.equal((await exported()).time,saved.time);
 await page.locator('#import-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{}')});await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Import failed'));assert.equal(await page.getByRole('dialog').isVisible(),false);
 const runDownload=page.waitForEvent('download');await click('Export replayable run');const runBytes=await readFile(await(await runDownload).path());await page.locator('#import-file').setInputFiles({name:'verified-run.json',mimeType:'application/json',buffer:runBytes});await click('Replace run');assert.equal((await exported()).time,saved.time);
 for(const [route,label] of [['Engineering reference','Export review JSON'],['Control & I/O','Export tags CSV'],['Alarms & historian','Export historian CSV'],['Quality & genealogy','Export genealogy CSV']]){await openRoute(route);const pending=page.waitForEvent('download');await click(label);assert.ok((await readFile(await(await pending).path())).length>30);}
 await page.getByRole('button',{name:'Dark',exact:true}).click();assert.equal(await page.locator('body').getAttribute('data-theme'),'dark');await page.getByRole('button',{name:'Light',exact:true}).click();
 await openRoute('Process overview');await page.addScriptTag({path:resolve('node_modules/axe-core/axe.min.js')});
 for(const theme of ['dark','light']){if(await page.locator('body').getAttribute('data-theme')!==theme)await click(theme==='dark'?'Dark':'Light');const a11y=await page.evaluate(async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa']}});return r.violations.filter(v=>['serious','critical'].includes(v.impact)).map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}));});assert.deepEqual(a11y,[],theme+' accessibility');}
 for(const width of [390,768,1440]){await page.setViewportSize({width,height:1000});for(const name of routes){await openRoute(name);const layout=await page.evaluate(()=>({overflow:document.body.scrollWidth>innerWidth,offenders:[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,12).map(e=>({tag:e.tagName,cls:e.className,right:e.getBoundingClientRect().right}))}));assert.equal(layout.overflow,false,name+' overflow at '+width+' '+JSON.stringify(layout.offenders));const dock=await page.locator('.control-dock').boundingBox();assert.ok(dock&&dock.y>=0&&dock.y+dock.height<=1001,'Control dock remains inside viewport');}}
 for(const alias of ['suite/','potato/','products/operations/','suite/products/operations/','demo/','studio/']){await page.goto(base+'/'+alias);await page.getByRole('heading',{name:'Process overview',exact:true}).waitFor();assert.equal(new URL(page.url()).pathname,new URL(base+'/').pathname);assert.equal(await page.locator('.asset-pin').count(),15);}
 await mkdir('/tmp/oia-qa',{recursive:true});
 await page.setViewportSize({width:1440,height:1100});await page.screenshot({path:'/tmp/oia-qa/potato-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/oia-qa/potato-mobile.png',fullPage:true});
 await writeFile('/tmp/oia-qa/result.json',JSON.stringify({base,routes:10,viewports:[390,768,1440],equipment:15,legacyAliases:6,consoleErrors:errors},null,2));
 await page.keyboard.press('Tab');assert.notEqual(await page.evaluate(()=>document.activeElement.tagName),'BODY');
 const vectorBrowser=await chromium.launch({args:['--disable-webgl']});try{const vectorPage=await vectorBrowser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});await vectorPage.goto(base+'/');await vectorPage.locator('#plant-canvas svg[role="img"]').waitFor();assert.equal(await vectorPage.locator('#plant-canvas').getAttribute('data-renderer'),'vector');await vectorPage.getByRole('button',{name:'Plan',exact:true}).click();await vectorPage.locator('[data-unit="fry"]').click();assert.equal(await vectorPage.locator('.inspector h2').innerText(),'Par-fry');await vectorPage.screenshot({path:'/tmp/oia-qa/potato-vector.png',fullPage:false});}finally{await vectorBrowser.close();}
 assert.deepEqual(errors,[]);console.log('PASS: ten routes, three viewports, spatial camera/overlays/three views, WebGL fallback, accessibility, 15 operated inspectors, Start/Stop/restart, model-control readback, all fault controls, receipts/orders/recipes, maintenance/sanitation, gateway/ERP, import/save/load/export, hold/resume, trip guards/recovery, quality release/dispatch, tag filtering, time lens, save/export, role restrictions, themes and keyboard focus.');
}finally{await browser?.close();if(server)await new Promise(r=>server.close(r));}
